# Generated by Django 5.1.3 on 2024-11-29 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('species', models.CharField(max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=30)),
                ('description', models.CharField(max_length=400)),
            ],
            options={
                'db_table': 'Pet',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
