# Generated by Django 5.1.3 on 2024-12-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0002_pet_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], default='D', max_length=1),
        ),
    ]
