# Generated by Django 5.1.3 on 2024-12-02 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0004_alter_pet_animal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('D', 'Dog'), ('C', 'Cat')], max_length=1),
        ),
    ]
