# Generated by Django 5.1.3 on 2024-12-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petapp', '0006_pet_added_by_pet_rest_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='rest_owner',
            new_name='petapp_owner',
        ),
    ]
