name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install Pillow

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PWD/petstore" >> $GITHUB_ENV
        
      - name: Run migrations
        run: |
          cd petstore/petstore
          python manage.py migrate

      - name: Run tests
        run: |
          cd petstore
          python manage.py test
